name: Jest and Codecov

on: push

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout main
        run: |
          git fetch --no-tags --depth=1 origin main
          git checkout origin/main
          git checkout ${{ github.sha }}
      - name: Install dependencies
        run: yarn install
      - name: Run Jest
        run: yarn test
      - name: Run Codecov
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
