name: Jest and Codecov

on: push

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch main (to compare)
        run: |
          git fetch origin main
      - name: Install dependencies
        run: yarn install
      - name: Run Jest
        run: yarn test
      - name: Run Codecov
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
